name: TimeTracker
version: '${project.version}'
main: me.roopekoo.timeTracker.TimeTracker
api-version: 1.18
authors: [ Roopekoo ]
description: Displays playtime toplist
commands:
  gettime:
    description: 'Show player playtime'
    usage: /<command> [playerName] <timeFormat>
  toptime:
    description: 'List players based on playtime'
    usage: /<command> [page] <timeFormat>
  playhistory:
    description: 'Show player playtime in certain time-range, e.g day/month/year playtime'
    usage: /<command> [playerName] [day/month/year] <timeFormat>
permissions:
  timetracker.gettime:
    description: "Allows to see other players' playtime"
    default: true
  timetracker.toptime:
    description: "Allows to see playtime top list"
    default: true
  timetracker.toptime.force:
    description: "Allows to update the toplist"
    default: op
  timetracker.playhistory:
    description: "Allows to see the playtimehistory of a player"
    default: true
